import type { Metadata } from 'next';
import RecoilContextProvider from './_recoil/recoilContextProvider';
import './globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='ko'>
      <body className='font-pre text-black'>
        <RecoilContextProvider>
          {children}
          <div id='modal' />
        </RecoilContextProvider>
      </body>
    </html>
  );
}
